[package]
name = "shgit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = "2.33.3"
derive_more = "0.99.16"
flate2 = "1.0.20"
hex = "0.4.3"
rand = "0.8.4"
sha-1 = "0.9.8"
